📦 add new bundle CustomerCompanyUserConnector
fond-of-impala/fond-of-impala pull request #46
Opened 2023-06-29 14:33 UTC by julianzimmermann

provides plugin for customer anonymization process (deletes company user before customer anonymization)

2023-07-03 07:04 UTC, daniel-rose requested changes

2023-07-03 07:04 UTC, daniel-rose commented on bundles/customer-company-user-connector/src/FondOfImpala/Zed/CustomerCompanyUserConnector/Business/Model/CompanyUserDeleter.php
> +        }
The performance for this lines is very bad. I would prefer to write an entity manager which delete company user entities by id customer.

2023-07-03 09:02 UTC, julianzimmermann commented on bundles/customer-company-user-connector/src/FondOfImpala/Zed/CustomerCompanyUserConnector/Business/Model/CompanyUserDeleter.php
> +        }
the facade uses preDeletePlugins, with EM those plugins would not be executed

2023-07-05 11:44 UTC, daniel-rose approved these changes

2023-07-19 10:05 UTC, merged